controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
<<<<<<< Updated upstream
=======
login:
    path: /admin/login
    controller: App\Controller\LoginController::login
login_check:
    path: /admin/login_check
logout:
    path: /admin/logout
admin:
    path: /admin
    controller: App\Controller\AdminController::admin
mj:
    path: /mj
    controller: App\Controller\MjController::mj
home:
    path: /
    controller: App\Controller\MjController::home
user_form:
    path: /admin/user-form
    controller: App\Controller\UserController::user_form
create_user:
    path: /admin/user-check
    controller: App\Controller\UserController::new_user
>>>>>>> Stashed changes
